language:
  - ruby

matrix:
  include:
    - os: linux

cache:
  directories:
  - node_modules
  - firenote/node_modules
  - $HOME/.electron
  - $HOME/.npm

install:
  - cd firenote
  - nvm install $NODE_VERSION
  - npm install npm -g
  - npm prune
  - npm install electron-packager -g
  - npm install

script:
  - ./darwin-build-vagrant.sh